AI04_S3/flask/my_app/routes/main_route.py
from flask import Blueprint, render_template, request, session, g, url_for
from werkzeug.utils import redirect
from my_app import db
from my_app.models.model import Ingr, Pp_rp, In_rp, Raw_rp, Review, Users


from my_app.forms import ReviewForm
from my_app.forms import RecipeForm


bp = Blueprint('main', __name__)

@bp.route('/')


def main():
    user_name = session.get('user_name')
    top_reviews = db.session.query(Review.recipe_id, db.func.sum(Review.rating)).group_by(Review.recipe_id).order_by(db.func.sum(Review.rating).desc()).limit(3).all()
    top_ratings = [i[1] for i in top_reviews]
    top_recipe_id = [i[0] for i in top_reviews]
    recipe_list = [db.session.query(Raw_rp.name).filter_by(id=i).first().name for i in top_recipe_id]
    # recipe_list = PP_recipes.query.

    results = db.session.query(Review.recipe_id, db.func.count(Review.rating), db.func.avg(Review.rating), Raw_rp.name, Raw_rp.minutes, Raw_rp.ingredients, Raw_rp.tags).filter(In_rp.ingr_id==Ingr.id).filter(In_rp.rp_id==Review.recipe_id).filter(Raw_rp.id==In_rp.rp_id).group_by(Review.recipe_id, Raw_rp.name, Raw_rp.minutes, Raw_rp.ingredients, Raw_rp.tags).order_by(db.func.count(Review.rating).desc()).limit(3).all()

    results2 = db.session.query(Review.recipe_id, db.func.count(Review.rating), db.func.avg(Review.rating), Raw_rp.name, Raw_rp.minutes, Raw_rp.ingredients, Raw_rp.tags).filter(Raw_rp.id==Review.recipe_id).group_by(Review.recipe_id, Raw_rp.name, Raw_rp.minutes, Raw_rp.ingredients, Raw_rp.tags).order_by(db.func.count(Review.rating).desc()).limit(3).all()

    # breakpoint()

    return render_template('index.html', results=results2, user_name = user_name)


@bp.route('/search')
def search():
    ingredient = request.args.get('kw', type=str, default='')
    if ingredient is None:
        return "Please input keywords", 400
    
    elif Ingr.query.filter_by(replaced = ingredient).first() is None:
        return f"{ingredient} not in database", 404

    else:
        ingr = f'%{ingredient}%'
        
        results = db.session.query(Review.recipe_id, db.func.count(Review.rating), db.func.avg(Review.rating), Raw_rp.name, Raw_rp.minutes, Raw_rp.ingredients, Raw_rp.tags).filter(In_rp.ingr_id==Ingr.id).filter(In_rp.rp_id==Review.recipe_id).filter(Raw_rp.id==In_rp.rp_id).filter(Ingr.replaced.ilike(ingr)).group_by(Review.recipe_id, Raw_rp.name, Raw_rp.minutes, Raw_rp.ingredients, Raw_rp.tags).order_by(db.func.count(Review.rating).desc()).limit(5).all()
        
        # breakpoint()


        recipe_ids = [i[0] for i in results]
        review_counts = [i[1] for i in results]

        return render_template('search.html', ids = recipe_ids, counts = review_counts, results=results, keyword=ingredient), 200

# breakpoint()

@bp.route('/recipe/<rp_id>')
def recipe(rp_id):

    recipe = Raw_rp.query.filter_by(id=rp_id).first()
    description = recipe.description
    minutes = recipe.minutes

    rating_avg = float(db.session.query(Review.recipe_id, db.func.avg(Review.rating)).filter(Review.recipe_id == rp_id).group_by(Review.recipe_id).first()[1])
    review_count = review_count = db.session.query(Review.recipe_id, db.func.count(Review.rating)).filter(Review.recipe_id == rp_id).group_by(Review.recipe_id).first()[1]
    review_list = db.session.query(Review.review, Review.rating).filter(Review.recipe_id == rp_id).all()


    form = ReviewForm()

    return render_template('recipe.html', recipe=recipe, rating_avg=rating_avg, review_count=review_count, review_list=review_list, description = description, minutes=minutes, form=form)
















@bp.route('/write_recipe', methods=('GET', 'POST'))
def write():
    form = RecipeForm()
    if request.method =='POST' and form.validate_on_submit():
        raw_recipe = Raw_rp(name = form.subject.data, 
                            minutes = form.time.data,
                            contributor_id = g.user.user_id,
                            ingredients = [form.ingredients1.data,form.ingredients2.data,form.ingredients3.data,form.ingredients4.data,form.ingredients5.data],
                            tags = form.tags.data)
        db.session.add(raw_recipe)
        db.session.commit()

        rp_id = Raw_rp.query.filter_by(name = form.subject.data).first().id
        ingr_id1 = Ingr.query.filter_by(replaced = form.ingredients1.data).first().id
        ingr_id2 = Ingr.query.filter_by(replaced = form.ingredients2.data).first().id
        ingr_id3 = Ingr.query.filter_by(replaced = form.ingredients3.data).first().id
        ingr_id4 = Ingr.query.filter_by(replaced = form.ingredients4.data).first().id
        ingr_id5 = Ingr.query.filter_by(replaced = form.ingredients5.data).first().id


        pp_recipe = Pp_rp(id = rp_id,
                            ingredient_id1 = ingr_id1,
                            ingredient_id2 = ingr_id2,
                            ingredient_id3 = ingr_id3,
                            ingredient_id4 = ingr_id4,
                            ingredient_id5 = ingr_id5,)
        
        # in_rp = In_rp()
        db.session.add(pp_recipe)
        db.session.commit()
        return redirect(url_for('main.index'))
    
    return render_template('write_recipe_form.html', form=form)







    # join1 = db.session.query(In_rp).join(Ingr).filter(Ingr.replaced.ilike('%vanilla%')).all()

    # join2 = db.session.query(In_rp, Ingr).filter(Ingr.replaced.ilike('%vanilla%')).all()

    # join3 = db.session.query(In_rp, Ingr, Review).filter(In_rp.ingr_id==Ingr.id).filter(In_rp.rp_id==Review.recipe_id).filter(Ingr.replaced.ilike('%vanilla%')).all()

    # join4 = db.session.query(Review.recipe_id).filter(In_rp.ingr_id==Ingr.id).filter(In_rp.rp_id==Review.recipe_id).filter(Ingr.replaced.ilike('%vanilla%')).all()

    # join5 = db.session.query(Review.recipe_id, db.func.count(Review.rating)).filter(In_rp.ingr_id==Ingr.id).filter(In_rp.rp_id==Review.recipe_id).filter(Ingr.replaced.ilike('%vanilla%')).group_by(Review.recipe_id).order_by(db.func.count(Review.rating).desc()).limit(5).all()

    # rating_avg = float(db.session.query(Review.recipe_id, db.func.avg(Review.rating)).filter(Review.recipe_id == rp_id).group_by(Review.recipe_id).first()[1])

    # review_count = db.session.query(Review.recipe_id, db.func.count(Review.rating)).filter(Review.recipe_id == rp_id).group_by(Review.recipe_id).first()

    # review_list = db.session.query(Review.review, Review.rating).filter(Review.recipe_id == 3470).all()

AI04_S3/flask/my_app/routes/user_routes.py
from os import error
from flask import Blueprint, render_template, url_for, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from my_app import db

from my_app.forms import ChangePassword, UserCreateForm
from my_app.models.model import Ingr, Pp_rp, In_rp, Raw_rp, Review, Users

from my_app.forms import UserCreateForm, UserLoginForm

import functools

bp = Blueprint('user', __name__, )

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if not user:
            user = Users(username=form.username.data,
                        password=generate_password_hash(form.password1.data))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.main'))
        else:
            flash('User already existing')
    return render_template('signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = Users.query.filter_by(username=form.username.data).first()
        if not user:
            error = "User does not exist"
        elif not check_password_hash(user.password, form.password.data):
            error = "Wrong password"
        if error is None:
            session.clear()
            session['user_name'] = user.username
            session['logged_in'] = True
            g.user = user
            return redirect(url_for('main.main')) 
        flash(error)
    return render_template('login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_name = session.get('user_name')

    if user_name == None:
        g.user = None
    else:
        g.user = db.session.query(Users).filter_by(username = user_name).first()
        # g.user = Users.query.get(user_name)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.main'))  




# breakpoint()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view


@bp.route('/my_page', methods=('GET', 'POST'))
def mypage():
    form = ChangePassword()

    if request.method == 'POST' and form.validate_on_submit():
        user = Users.query.filter_by(u = g.user.u).first()
        if g.user != user:
            flash('no authority')
            return redirect(url_for('user.mypage'))
    
        else:
            user.password = generate_password_hash(form.password.data)
            db.session.commit()
            render_template('my_page.html', form=form)

    return render_template('my_page.html', form=form)


@bp.route('/modify/<int:user_id>', methods=('GET', 'POST'))
@login_required
def modify(user_id):
    form = ChangePassword()

    user = Users.query.filter_by(u = user_id).first()
    
    if g.user != user:
        flash('no authority')
        return redirect(url_for('user.mypage'))
    
    else:
        user.password = generate_password_hash(form.password.data)
        db.session.commit()
        render_template('my_page.html', form=form)


@bp.route('/delete/<int:user_id>')
@login_required
def delete(user_id):
    user = Users.query.filter_by(u = user_id).first()
    if g.user != user:
        flash('no authority')
        return redirect(url_for('user.mypage'))
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('main.main'))

AI04_S3/flask/my_app/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

AI04_S3/flask/my_app/templates/index copy 2.html
<html>
  <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

  </head>
  <body>

    <form method="get" action="{{ url_for('main.search', name='kw') }}">
      <div class="input-group" style='font-size: 20px;'>
        <input type="text" class="form-control kw" name="kw" id="kw" value="{{kw or '' }}" placeholder="Enter search value">
        <input type="submit" class="btn btn-primary" style="width:120px;background-color: maroon; border:none;" value="Search">
      </div>  
    </form>

      <div class="jumbotron">
        <h1 style="font-size:50px; text-align:center; margin-top:0;">Most Popular recipes</h1>
        <br>
        <br>
        <table class="table table-striped table-bordered" style='color:white;'>
          <thead>
            <tr>
              {% for result in results %}
              <th colspan=4>
                <a href="{{ url_for('main.recipe', rp_id=result.recipe_id) }}">{{result.name}}</a>
              </th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr align='center'>

              <td colspan=4><img src="../static/images/wonderful_salsa.jpg" width=80%> </td>
              <td colspan=4><img src="../static/images/oven_bbq_ribs.jpg" width=80%> </td>
              <td colspan=4><img src="../static/images/crock pot chops.jpg" width=80%> </td>
            </tr>
            <tr align='center' style='font-size:20'>
              {% for result in results %}
              <td></td>
              <td>Rating : </td>
              <td> {{'%0.2f' %result[2]|float}} </td>
              <td></td>
              {% endfor %}

            </tr>
            <tr align='center' style='font-size:20'>
              {% for result in results %}
              <td> </td>
              <td >Reviews : </td>
              <td> {{result[1]}} </td>
              <td> </td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

AI04_S3/flask/my_app/templates/index copy.html
<html>
  <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script> -->
  </head>
  <body>

    <!-- <div class="container">
      <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw or '' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div> -->

    <!-- <form method="POST" action="/api/prediction">
      <div class="input-group">
        <span class="input-group-text" style="display: inline-block; text-align:center; width:120px;color:white;background-color: rgb(0, 0, 0); border:none;">Key / Value</span>
        <select name="key" class="form-control" id="exampleFormControlSelect1">
          <option value="link_end">Identifier</option>
          <option value="abstract">Abstract</option>
          <option value="title">Title</option>
        </select>
        <input name="value" type="text" aria-label="end_date" class="form-control" placeholder="Enter search value">
      </div>
    
      <div class="input-group">
        <span class="input-group-text" style="display: inline-block; text-align:center; width:120px;color:white;background-color: rgb(65, 65, 65); border:none;">Select Model</span>
        <select name="model_name" class="form-control" id="exampleFormControlSelect1">
          <option value="model_QI">model_QI</option>
          <option value="model_all">model_all</option>
          <option value="model_opt">model_opt</option>
          <option value="model_sze">model_sze</option>
          <option value="model_dl">model_dl</option>
        </select>
        <input type="submit" class="btn btn-primary" style="width:120px;background-color: maroon; border:none;" value="search">
      </div> 
    </form> -->




    <form method="get" action="{{ url_for('main.search', name='kw') }}">
      <div class="input-group" style='font-size: 20px;'>
        <input type="text" class="form-control kw" name="kw" id="kw" value="{{kw or '' }}" placeholder="Enter search value">
        <input type="submit" class="btn btn-primary" style="width:120px;background-color: maroon; border:none;" value="Search">
      </div>  
    </form>


    <!-- <div class="input-group-append">
      <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
    </div> -->







      <div class="jumbotron">
        <h1 style="font-size:50px; text-align:center; margin-top:0;">Most Popular recipes</h1>
        <br>
        <br>
        <table class="table table-striped table-bordered" style='color:white;'>
          <thead>
            <tr>
              {% for recipe in recipes %}
              <th colspan=4>{{recipe}}</th>
              <!-- <th>TEST2</th>
              <th>TEST3</th> -->
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr align='center'>

              <td colspan=4><img src="../static/images/wonderful_salsa.jpg" width=80%> </td>
              <td colspan=4><img src="../static/images/oven_bbq_ribs.jpg" width=80%> </td>
              <td colspan=4><img src="../static/images/chocolate_chip_cookies.jpg" width=80%> </td>
            </tr>
            <tr align='center' style='font-size:20'>
              <td></td>
              <td>Rating : </td>
              <td> 5 </td>
              <td></td>
              <td></td>
              <td>Rating : </td>
              <td> 5 </td>
              <td></td><td></td>
              <td>Rating : </td>
              <td> 5 </td>
              <td></td>
            </tr>
            <tr align='center' style='font-size:20'>
              <td> </td>
              <td >Reviews : </td>
              <td> 5 </td>
              <td> </td>
              <td> </td>
              <td >Reviews : </td>
              <td> 5 </td>
              <td> </td>
              <td> </td>
              <td >Reviews : </td>
              <td> 5 </td>
              <td> </td>
            </tr>
          </tbody>
          
        </table>


        
        <table class="table table-striped table-bordered" style='color:white;'>
          <thead>
            <tr>
              {% for result in results %}
              <th colspan=4>
                <a href="{{ url_for('main.recipe', rp_id=result.recipe_id) }}">{{result.name}}</a>
              </th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr align='center'>

              <td colspan=4><img src="../static/images/wonderful_salsa.jpg" width=80%> </td>
              <td colspan=4><img src="../static/images/oven_bbq_ribs.jpg" width=80%> </td>
              <td colspan=4><img src="../static/images/chocolate_chip_cookies.jpg" width=80%> </td>
            </tr>
            <tr align='center' style='font-size:20'>
              {% for result in results %}
              <td></td>
              <td>Rating : </td>
              <td> {{'%0.2f' %result[2]|float}} </td>
              <td></td>
              {% endfor %}

            </tr>
            <tr align='center' style='font-size:20'>
              {% for result in results %}
              <td> </td>
              <td >Reviews : </td>
              <td> {{result[1]}} </td>
              <td> </td>
              {% endfor %}
            </tr>
          </tbody>
          
        </table>


        <!-- <hr class="my-4"> -->
        <!-- <p>
          <style>
            .scites {
              color : yellow;
              font-weight: bold;
            }
            .input-group{
              margin-block-end:10px;
            }
          </style>
        </p> -->
      </div>

    </div>

    <!-- <h1>Welcome to index page</h1>
    <ul>
      {% for recipe in recipes %}
      <li><a href="/detail/">{{recipe}}</a></li>
      {% endfor %}
    </ul> -->
  </body>
</html>

AI04_S3/flask/my_app/templates/index.html
<html>
  <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    
    
  </head>
  <body>

    <h1>Welcome to index page</h1>
    <ul>
      {% for recipe in recipes %}
      <li><a href="/detail/">{{recipe}}</a></li>
      {% endfor %}
    </ul>
  </body>
</html>

AI04_S3/flask/my_app/templates/login.html
<html>
    <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

  </head>
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="jumbotron_login">
            <h1 style="font-size:50px; text-align:center; margin-top:50px; color:white;">Log In</h1>
            <form method="post" class="post-form">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="username">User Name&nbsp;&nbsp;</label>
                    <input type="text" class="form-control" name="username" id="username"
                        value="{{ form.username.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="password">Password&nbsp;&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password" id="password"
                        value="{{ form.password.data or '' }}">
                </div>
                <button type="submit" class="btn btn-primary" style='font-size:20px; color:white; background:rgba(0,0,0,0); border:none; cursor:pointer; display:inline-block;'>Log In</button>

                
            </form>
        </div>
    </body>

AI04_S3/flask/my_app/templates/my_page.html
<html>
    <head>
    <title>
      My Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

  
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="jumbotron_mypage">
            <h1 style="font-size:50px; text-align:center; margin-top:50px; color:white;">My Page</h1>

            <h2 class='my_page'>User Name : {{g.user.username}}</h2>
            <!-- <h2 class='my_page'>Password : {{g.user.password|string}}</h2> -->
            <h2 class='my_page'>ID : {{g.user.u}}</h2>




            <!-- <form action="{{ url_for('user.modify', user_id=g.user.u) }}" method="post" class="my-3">
                <div class="form-group">
                    <textarea name="content" id="content" class="form-control" rows="1" style="margin-bottom:10px" placeholder="한줄평을 입력해 주세요."></textarea>
                </div>
                <input type="submit" value="submit" class="btn btn-primary">
            </form> -->



            <form method="post" class="post-form">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}

                <div class="form-group">
                    <label for="password">New Password&nbsp;&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password" id="password"
                        value="{{ form.password.data or '' }}">
                </div>
                <button type="submit" class="btn btn-primary" style='font-size:20px; color:white; background:rgba(0,0,0,0); border:none; cursor:pointer; display:inline-block;'>
                    Change Password</button>
            </form>


            <a class="delete btn btn-sm btn-outline-secondary" href="{{ url_for('user.delete', user_id=g.user.u) }}">Delete User</a>

            <!-- <a href="#" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{ url_for('user.delete', user_id=g.user.u) }}">Delete</a> -->



        </div>
    </body>

AI04_S3/flask/my_app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <!-- <a class="navbar-brand" href="{{ url_for('main.main') }}">Home</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button> -->

    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="navbar-brand" href="{{ url_for('main.main') }}"><b>Home</b></a>
            </li>
        </ul>
            
        
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.logout') }}"><b>{{ g.user.username }} (Log out)</b></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('main.write') }}"><b>Post Recipe</b></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.mypage') }}"><b>My Page</b></a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.signup') }}"><b>Sign Up</b></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.login') }}"><b>Log in</b></a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

AI04_S3/flask/my_app/templates/search.html
<html>
  <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search_bootstrap.css') }}">

  </head>
  <body>
    {% include "navbar.html" %}
   
    <div class="container">
      <div class="jumbotron">
        <h1 style='color:rgb(255, 102, 0)'> Search results for "{{keyword}}"</h1>
        <br>
        <br>
        {% for result in results %}
          {% set id = result.recipe_id %}
          {% set count = result[1] %}
          {% set rating = result[2] %}
          {% set name = result.name %}
          {% set time = result.minutes %}
          {% set ingredients = result.ingredients %}
          {% set tags = result.tags %}

          <div class="results"> 
            <div classs="name">
              <h1>
                <a href="{{ url_for('main.recipe', rp_id=id) }}">{{name}}</a>
              </h1>
              <a ><b>Time</b> : {{time}}min</a>
              <br>
              <a><b>Ingredients</b> : {{ingredients}}</a>
              <br>
              <a><b>Tags</b> : {{tags}}</a>
              <br>
            </div>
            <div class="reviews">
              <a><b>Rating</b> : {{'%0.2f' %rating|float}}</a>
              <br>
              <a><b>Reviews</b> : {{count}}</a>
              <br>
              <br>
            </div>
          </div>
        {% endfor %}
        



        <!-- {% for id in ids %}
            {% set item_1 = ids[loop.index-1] %}
            {% set item_2 = counts[loop.index-1] %}
            {% set item_3 = results[loop.index-1][2] %}
            <h1> {{item_1}}, {{item_2}}, {{item_3}}</h1>

        {% endfor %} -->
        

<!-- 

      {% for id in ids %}
        {% for count in counts %}
        {{id, count}} <br>
        {% endfor %}
      {% endfor %} -->


      </div>

    </div>
  </body>
</html>

AI04_S3/flask/my_app/templates/signup.html
<html>
    <head>
        <title>
            Sign up Page
          </title>
          <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
          <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">
    </head>
    <body> 
        {% include "navbar.html" %}
    
        <div class="jumbotron_login">
            <h1 style="font-size:50px; text-align:center; margin-top:50px; color:white;">Sign Up</h1>
            <form method="post" class="post-form">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="username">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User name&nbsp;&nbsp;</label>
                    <input type="text" class="form-control" name="username" id="username"
                        value="{{ form.username.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="password1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Password&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password1" id="password1"
                        value="{{ form.password1.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="password2">Reconfirm password&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password2" id="password2"
                        value="{{ form.password2.data or '' }}">
                </div>
                <button type="submit" class="btn btn-primary" style='font-size:20px; color:white; background:rgba(0,0,0,0); border:none; cursor:pointer; display:inline-block;'>create</button>
            </form>
        </div>
    </body>